### PR TITLE
[Enhancement] Add theme color meta tag for improved user experience

### PR DESCRIPTION
**Pull request by Ahmedsaed**
# Description

Defining the theme-color will allow the client (browser's address bar, task switcher, notification panel, etc...) to adapt to the theme of the app resulting in better user experience and overall better aesthetics.

This is how it looks before: 
Screenshot from 2024-01-06 23-01-50

This is how it looks after:
Screenshot from 2024-01-06 23-04-41

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist (check all that don't apply as well):

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] [No need for comments] I have commented my code, particularly in hard-to-understand areas 
- [X] [No documentation is needed] I have made corresponding changes to the documentation (if needed)
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by KL13NT — APPROVED** [review]

**Comment by KL13NT** [comment]
Hello @Ahmedsaed, thank you for opening this PR. I'll be accepting this one since the change is tiny but please make sure to follow our contribution guide for any future contributions. We require an open Issue to be opened before PRs to make sure we're aligned on the change. This is to avoid wasting time on "will-not-fix" tasks, etc.

Thank you again! 🥳

**Comment by Ahmedsaed** [comment]
Hi @KL13NT ,

Thank you for reviewing and merging the PR! I appreciate your feedback and guidance. I'll make sure to follow the contribution guide for any future contributions.

Thanks again! 🎉

**Comment by KL13NT** [comment]
@all-contributors please add @Ahmedsaed for development

**Comment by KL13NT** [comment]
@all-contributors please add @Ahmedsaed for code

**Pull request merged**
