### PR TITLE
feat: add proper meta tags with an open graph image

### PR DESCRIPTION
**Pull request by karimshalapy**
# Proposed changes

- Adds the proper meta tags: open graph, Twitter, and default meta tags
- Adds the open graph image as a static asset

## Types of changes

- [x] ✨ Feature

## Does this introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by karimshalapy** [comment]
This relates to #3 and #11 although I don't know if this should entirely close #3

**Comment by karimshalapy** [comment]
@KL13NT Make sure that `/og.png` serves the image properly, I tried locally and it works, I am not sure why it doesn't in the preview. I think you might need to tweak something in the Netlify settings.

**Comment by karimshalapy** [comment]
After checking, I can see that Netlify optimizes the deployment by checking the changed files and only uploading these files, this means we might need a restart of the currently running server if it doesn't restart with each deployment because I changed the vite config to include the `og.png` as a static asset.

**Review by KL13NT — APPROVED** [review]
LGTM

**Comment by KL13NT** [comment]
> After checking, I can see that Netlify optimizes the deployment by checking the changed files and only uploading these files, this means we might need a restart of the currently running server if it doesn't restart with each deployment because I changed the vite config to include the `og.png` as a static asset.

What you faced is probably the PWA caching its own assets. Netlify responds with 404 for files that don't exist. I'll set it up to redirect to the index.html instead to make sure the SPA is loaded regardless of the page you access.

**Pull request merged**
